### ISSUE TITLE
Document how to `fill_form` for a changeset with associations

### ISSUE THREAD

**Issue by mayel** [germsvel/phoenix_test#17] opened 2024-02-09 23:30 UTC
How should one `fill_form` or `submit_form` when you have inputs with a `name` such as `account[email_address]` or even `account[credential][password]`?

I have tried:
```
    account: [
      email_address: email, 
      credential: [password: password]
    ]
```

```
    %{
        "account" => %{
          "email_address" =>  email,
          "credential" => %{"password" => password}
        }
      }
```

```
    %{
      "account[email_address]" => email,
      "account[credential][password]" => password
    }
```

ending up with this one which seems to work but isn't very ergonomic:
```
      %{
        "name='account[email_address]'" => email,
        "name='account[credential][password]'" => password
      }
```

**Comment by randycoulman** [comment] 2024-02-10 04:28
@mayel I was looking at this as well. Internally, for LiveView forms, it looks like PhoenixTest is using [Phoenix.LiveViewTest.form/3](https://hexdocs.pm/phoenix_live_view/Phoenix.LiveViewTest.html#form/3) to fill in the form fields, so whatever works there should work here.

I've been able to get a simple form (no nested fields) to work with `account: [name: "Whatever"]`. It seems like your first option above should work, but I haven't tried with nested fields yet.

If you're using a LiveView form, then maybe you could try getting it to work with just the `email_address` field first, then add the nested field after that?

**Comment by germsvel** [comment] 2024-02-10 11:25
Hi @mayel, thanks so much for opening this issue. Seems like I didn't document that well at all! 😅 

You should be able to pass nested maps as the final argument in `fill_form/3` and `submit_form/3`. The nested maps should match the nesting in your inputs. 

So for an `<input name="account[email_address]">`, you should be able to use something like this: 

```elixir
...
|> fill_form("form", account: %{email_address: "mayel@example.com"})

# also works with submit_form
...
|> submit_form("form", account: %{email_address: "mayel@example.com"})
```

I tried to improve the documentation in https://github.com/germsvel/phoenix_test/commit/680938926b5d6024b0e3061dcff01999c74b2c7b, but if you have thoughts on how I could make it even clearer, I'd love to know (and always happy to review PRs).

**Comment by mayel** [comment] 2024-02-10 12:37
Thanks both! :) 

@germsvel Unfortunately I get this error when trying that:
```
     ** (ArgumentError) Could not find element with selector "#signup-form [name=account]"
     code: |> fill_form("#signup-form",
     stacktrace:
       (phoenix_test 0.2.2) lib/phoenix_test/query.ex:9: PhoenixTest.Query.find!/2
       (elixir 1.16.1) lib/enum.ex:987: Enum."-each/2-lists^foreach/1-0-"/2
       (phoenix_test 0.2.2) lib/phoenix_test/live.ex:122: PhoenixTest.Driver.PhoenixTest.Live.fill_form/3
```

Here is the actual HTML of the rendered form if that helps:
```
<form action="#" method="post" id="signup-form">
  <input name="_csrf_token" type="hidden" hidden="" value="xyz">
  <input type="hidden" name="account[email][_persistent_id]" value="0">
  <div>
    <label for="signup-form_email_email_address" class="label">
      <span class="text-xs label-text">
        Email address
      </span>
    </label>
    <input class="w-full h-10 text-sm rounded input input-bordered" id="signup-form_email_0_email_address"
      name="account[email][email_address]" placeholder="alice@email.com" type="email">
  </div>

  <input type="hidden" name="account[credential][_persistent_id]" value="0">
  <div class="mt-3">
    <div>
      <label class="label" for="signup-form_credential_0_password">
        <span class="text-xs label-text">
          Choose a password (10 characters minimum)
        </span>
      </label>
      <input class="w-full h-10 text-sm rounded input input-bordered" id="signup-form_credential_0_password"
        name="account[credential][password]" placeholder="Type a strong password" type="password">
    </div>
  </div>
  <div class="mt-3">
    <div>
      <label class="label" for="signup-form_credential_0_password_confirmation">
        <span class="text-xs label-text">
          Confirm your password
        </span>
      </label>
      <input class="w-full h-10 text-sm rounded input input-bordered"
        id="signup-form_credential_0_password_confirmation" name="account[credential][password_confirmation]"
        placeholder="Enter the same password again" type="password">
    </div>
  </div>
  <div class="mt-6">
    <span class="block w-full rounded-md shadow-sm">
      <button type="submit" class="flex w-full normal-case btn btn-primary place-content-center">
        Sign up
      </button>
    </span>
  </div>
  <div class="flex py-4 pb-2 mt-6 text-xs border-t border-base-content/20 place-content-center">
    <p>
      Do you already have an account?
      <a href="/login" class="link link-primary" data-phx-link="redirect" data-phx-link-state="push">Log in</a>
    </p>
  </div>
</form>

**Comment by germsvel** [comment] 2024-02-10 15:05
@mayel, can you double check that you're using the latest version of PhoenixTest? (version 0.2.2). 

I tried reproducing the error with the form you copied, but I'm not getting one. You can see my attempt here https://github.com/germsvel/phoenix_test/compare/main...test-issue-17-form

**Comment by mayel** [comment] 2024-02-10 15:10
Hmm strange. Yes I'm on:

- PhoenixTest 0.2.2 
- phoenix_live_view, "0.20.1"
- phoenix_html, "3.3.3"
- phoenix, "1.7.11"

**Comment by lcezermf** [comment] 2024-02-13 19:31
Assuming you have the input `<input class="w-full h-10 text-sm rounded input input-bordered" id="signup-form_email_0_email_address"
      name="account[email][email_address]" placeholder="alice@email.com" type="email">`

Shouldn't the call to fill_form to be

```elixir
...
|> fill_form("form", account: %{email: %{email_address: "mayel@example.com"}})

# also works with submit_form
...
|> submit_form("form", account: %{email: %{email_address: "mayel@example.com"}})
```

**Comment by mayel** [comment] 2024-02-13 20:03
thanks @lcezermf but I still get this error when trying that:
```
 ** (ArgumentError) Could not find element with selector "form [name=account]"
     code: |> fill_form("form",
     stacktrace:
       (phoenix_test 0.2.4) lib/phoenix_test/query.ex:9: PhoenixTest.Query.find!/2
       (elixir 1.16.1) lib/enum.ex:987: Enum."-each/2-lists^foreach/1-0-"/2
       (phoenix_test 0.2.4) lib/phoenix_test/live.ex:115: PhoenixTest.Driver.PhoenixTest.Live.fill_form/3

**Comment by germsvel** [comment] 2024-02-14 13:22
@mayel thanks for the patience and perseverance. I think I finally got a fix for the error you were seeing. Turns out I was missing testing nested forms on one code path. The fix is on `main` right now, but it'll be on the next published version.

**Comment by mayel** [comment] 2024-02-15 10:30
@germsvel no worries, thank you for taking the time! I'm still getting the same error using `main`.
I'm guessing that maybe even when the `action_form?` code path is being triggered, it may be calling `PhoenixTest.submit_form` may be delegating back to `PhoenixTest.Live` since the error is triggered by the LV function https://hexdocs.pm/phoenix_live_view/Phoenix.LiveViewTest.html#render_submit/2 which says "must point to a single element on the page with a phx-submit attribute in it":
```
       (phoenix_live_view 0.20.6) lib/phoenix_live_view/test/live_view_test.ex:1102: Phoenix.LiveViewTest.call/2
       (phoenix_test 0.2.4) lib/phoenix_test/live.ex:166: PhoenixTest.Driver.PhoenixTest.Live.submit_form/3

**Comment by mayel** [comment] 2024-02-15 10:32
maybe it needs to be
```
      action_form?(session, form.selector) ->
        session.conn
        |> PhoenixTest.Static.build()
        |> PhoenixTest.Static.submit_form(form.selector, form.form_data)

**Comment by germsvel** [comment] 2024-02-15 11:25
@mayel I know you included a copy of the form (in https://github.com/germsvel/phoenix_test/issues/17#issuecomment-1936997130) you're trying to test. 

Can you include the test itself you're running that's failing? And can you provide the full error you're seeing?

**Comment by mayel** [comment] 2024-02-15 11:51
sure thing: https://github.com/bonfire-networks/bonfire_ui_me/blob/main/test/controllers/signup_test.exs#L86

```
  1) test success (with PhoenixTest) (Bonfire.UI.Me.SignupController.Test)
     extensions/bonfire_ui_me/test/controllers/signup_test.exs:86
     ** (ArgumentError) element selected by "form#signup-form" does not have phx-submit attribute
     code: |> submit_form("form#signup-form",
     stacktrace:
       (phoenix_live_view 0.20.6) lib/phoenix_live_view/test/live_view_test.ex:1102: Phoenix.LiveViewTest.call/2
       (phoenix_test 0.2.4) lib/phoenix_test/live.ex:166: PhoenixTest.Driver.PhoenixTest.Live.submit_form/3
       extensions/bonfire_ui_me/test/controllers/signup_test.exs:104: (test)

**Comment by mayel** [comment] 2024-02-15 11:53
btw seems this error is more related to #17 compared to the one I was getting [above](https://github.com/germsvel/phoenix_test/issues/17#issuecomment-1942341568)

**Comment by germsvel** [comment] 2024-02-15 12:45
Thanks for the link to the test! 

It seems that you're going through a regular form submit in a LiveView _and_ your test is using `render_submit`. 

I updated PhoenixTest to handle regular form submissions in LiveView pages through `fill_form` + `click_button`, but I didn't update `submit_form` to do that. I'll do that as soon as I can.

In the meantime, you could try updating the test to use `fill_form` + `click_button`. I think that should work. 

```elixir
test "success (with PhoenixTest)" do
    conn = conn()
    email = email()
    password = password()

    pt =
      conn
      |> visit("/")

    pt
    |> click_link("Create an account")
    |> assert_has("button", "Accept")
    |> fill_form("form#signup-form",
      account: %{
        email: %{email_address: email}, 
      })
    |> click_button("Sign up")
```

And if it doesn't, it probably means my understanding of what's failing here is wrong.

**Comment by mayel** [comment] 2024-02-15 13:15
Hmm I had tried that as well but if memory serves I'm now getting a different error:
```
     ** (ArgumentError) Could not find element with selector "form#signup-form"
     code: |> click_button("Sign up")
     stacktrace:
       (phoenix_test 0.2.4) lib/phoenix_test/query.ex:9: PhoenixTest.Query.find!/2
       (phoenix_test 0.2.4) lib/phoenix_test/static.ex:111: PhoenixTest.Driver.PhoenixTest.Static.fill_form/3
       (phoenix_test 0.2.4) lib/phoenix_test/static.ex:124: PhoenixTest.Driver.PhoenixTest.Static.submit_form/3
```

Seems strange that it complains `form#signup-form"` on the click_button step and not the fill_form one...

**Comment by mayel** [comment] 2024-02-15 13:16
At least now it's using `PhoenixTest.Static` instead of `Live`

**Comment by germsvel** [comment] 2024-02-15 13:58
@mayel is there any chance that you could create a simplified version of your `bonfire_ui_me` repo that reproduces the test error? I tried cloning it and getting it set up to run the test, but `mix deps.get` fails because it's trying to load a local `:bonfire_epics` project of some kind. 

```elixir
Error while loading project :bonfire_epics at <mypath>/bonfire_ui_me/deps/bonfire_epics
** (Code.LoadError) could not load <mypath>/bonfire_ui_me/deps/bonfire_epics/mess.exs. Reason: enoent
    (elixir 1.16.0) lib/code.ex:2143: Code.find_file!/2
    (elixir 1.16.0) lib/code.ex:1424: Code.eval_file/2
    <mypath>/bonfire_ui_me/deps/bonfire_epics/mix.exs:1: (file)

```

**Comment by germsvel** [comment] 2024-02-22 10:23
@mayel I'm going to close this because I can't reproduce the error. If you have an easy way to reproduce this or have more info, let me know! Happy to reopen this issue, or we can open a new one.

**Closed by germsvel** 2024-02-22 10:23 UTC

**Comment by mayel** [comment] 2024-04-29 15:43
just a note that the new form API avoids these issues in a nice way 😄 ❤️
